### ISSUE TITLE
Some questions about the dataset???

### ISSUE THREAD

**Issue by duy1009** [ntnu-arl/sevae#1]
I'm a Vietnam student trying to redeploy this project. I got some struggle about the dataset. I found that this dataset was created from agile_autonomy, gazebo environment, and flightmare environment. But I have some questions about this, like how to name the label on this dataset, how to recreate this dataset? Can you give me some example about the template of this dataset?

**Comment by HuanNguyenARL** [comment]
@mihirk284 Can you have a look at this question?

**Comment by mihirk284** [comment]
Hello @duy1009,

The synthetic datasets that were used to train the Semantically-enhanced VAEs was obtained exclusively from the [Aerial Gym Simulator](https://github.com/ntnu-arl/aerial_gym_simulator) and Gazebo environments. Not from the simulators that are mentioned above.  The Gazebo environments provided unlabeled depth images, which were used to train the VAE without any guidance from semantic labels.

A depth camera and segmentation camera was used within the Aerial Gym Simulation environment and the thin obstacles were specifically having a segmentation label. We used the segmentation label to specifically provide higher weight to the pixels in the depth image corresponding to the thin obstacles.

Additional real-world data was obtained from thy NYU-depth-dataset-v2 and self-collected handheld datasets. Very few of the self-collected images were labeled for thin features manually using image processing software, while most of the images were only used to train for depth reconstruction.

**Comment by guglielmo610** [comment]
Hello, can I ask you how did you perform the data collection with Aerial Gym Simulator? I ask this because I cannot find a code available to perform it in that specific environment (at least I couldn't find it in the Aerial Gym github).
What I am trying to do is to adapt the file "generate_data_info_gain.py" present in ORACLE folder, to the gym simulator, but I am finding some difficulties due to differences between the 2 simulators...

**Comment by HuanNguyenARL** [comment]
Hi @guglielmo610, for the Aerial Gym Simulator part, we placed the depth camera and segmentation camera randomly in the environment and collected the depth image + segmentation mask (@mihirk284 can you help him with this?). **The drone was not rolled out in Aerial Gym Simulator** in this work. The dataset to train the seVAE includes the ones from Aerial Gym Simulator + other sources (Gazebo, real-world data).

Then to train the ORACLE, we used the rolled-out data in Gazebo (which is basically what we have when running "generate_data_info_gain.py"). We need [a script](https://github.com/ntnu-arl/sevae/blob/main/sevae/utils/create_latent_pickles_from_ORACLE_datasets.py) to run the seVAE and convert the depth images to latent vectors + this [script](https://github.com/ntnu-arl/ORACLE/blob/main/process/data_processing_sevae.py) to create the dataset to train ORACLE.

**Comment by guglielmo610** [comment]
Yes exactly, I would need that because I would like to fine-tune ORACLE with the seVAE dataset (or at least a dataset with thin obstacles like the ones present in the Gym Simulator)

**Comment by HuanNguyenARL** [comment]
Hi @guglielmo610, I updated the link to the data-processing script in the above comment (please check the README for how to run it). You can use [this script](https://github.com/ntnu-arl/sevae/blob/main/sevae/utils/create_latent_pickles_from_ORACLE_datasets.py) to generate the latent pickle files from seVAE.

**Comment by guglielmo610** [comment]
Thank you very much, really appreciate it
